### ISSUE TITLE
Profile Switcher seems to be missing from package control

### ISSUE THREAD

**Issue by pavel-alay** [tonsky/sublime-profiles#1]
I cannot install it via `Package Control: Install Package` nor cannot find on https://packagecontrol.io:
https://packagecontrol.io/packages/Profile%20Switcher

**Comment by tonsky** [comment]
It’s been stuck in Package Control limbo for over a month :( https://github.com/wbond/package_control_channel/pull/8199

**Comment by pavel-alay** [comment]
As for now I've installed it via `Package Control: Add Repository` → `https://github.com/tonsky/sublime-profiles`.
And then `Package Control: Install Package` → `sublime-profiles`.

**Comment by pavel-alay** [comment]
Fixed: https://packagecontrol.io/packages/Profile%20Switcher
