### ISSUE TITLE
Switch Profile option not available after restart

### ISSUE THREAD

**Issue by evanirla** [tonsky/sublime-profiles#4]
When I restart sublime text, all my profiles seem to disappear. They still exist in the extension data folder, but they don't show up when I type "Profiles:"

![image](https://user-images.githubusercontent.com/30964298/114218172-4e83ce80-9926-11eb-9170-89e0f2546485.png)

**Comment by tonsky** [comment]
Any messages in console (View -> Show Console)?

**Comment by zznixt07** [comment]
same problem. It seems the problem occurs because `sublime.packages_path()` in `profiles.py` returns an empty string.

**Comment by tonsky** [comment]
Resolved in #5, plugin release 2.0.3
